#!/bin/bash

PREFIX=/usr/share

SEEN=$PREFIX/subtube/resources/seen.lst
SUBSCRIBES=$PREFIX/subtube/resources/subscribes
SUBTUBE_QUEUE=$PREFIX/subtube/resources/subtube_queue
SUBTUBE_TITLE=$PREFIX/subtube/resources/subtube_title.db
PLAYING_ICON=$PREFIX/subtube/resources/subtube-playing.png
YOUTUBE_ICON=$PREFIX/subtube/resources/subtube_youtube.png
THUMBNAILS=$PREFIX/subtube/resources/thumbnails
NAMES=$PREFIX/subtube/resources/subscribes_names

thumbnail(){
    wget -cq "https://i3.ytimg.com/vi/$1/hqdefault.jpg" -O $THUMBNAILS/$1.jpg
}

viewer(){
    alacritty --class subtube_viewer -e youtube-viewer &> /dev/null &
}

progress_bar(){
    done=$1
    total=$2
    percentage=$(($done*100/$total))

    bar_width=$3
    bar_tiles=$((bar_width*percentage/100))
    sep=$(echo -en "\u2014")
    bar=$(seq -s "$sep" $(($bar_tiles+1)) | sed 's/[0-9]//g')

    space_tiles=$(($bar_width-$bar_tiles))
    spaces=""
    for ((i=0; i<$space_tiles; i++)); do spaces=" $spaces"; done

    res="$bar$spaces"

    notify-send -t 4000 -i 'none' -u normal "SUBTUBE - Update" "<span>$res</span>"
}

update(){
    wget -q --spider http://google.com

    if [[ $? -gt 0 ]]; then
        notify-send -t 4000 -i 'none' -u critical "SUBTUBE" "No internet connection"
        exit 1
    fi
    if [[ -f /tmp/subtube_update.pid ]]; then
        notify-send -i 'none' -u critical "Subtube" "Update already in progress, wait..."
        exit 0
    else
        touch /tmp/subtube_update.pid
    fi
    i=0
    sub_i=0
    subcount=$(cat $SUBSCRIBES | wc -l)
    while read line; do
        sub_i=$((sub_i+1))
        if [[ $1 != "secret" ]]; then
            progress_bar $sub_i $subcount 30
        fi
        vid_ids=$(wget -qO- $line | grep "ux-thumb-wrap"| head -n 5 | cut -d\" -f4 | cut -d\= -f2)
        while read vid_id; do
            if [[ ! -z $(grep -e "^$vid_id$" $SEEN) ]]; then
                continue
            else
                [[ -z "$vid_id" ]] && continue
                if [[ $1 != "init" ]]; then
                    thumbnail $vid_id
                fi
                title=$(wget --quiet -O - "https://www.youtube.com/watch?v=$vid_id" | paste -s -d " " | sed -e 's!.*<head>\(.*\)</head>.*!\1!' | sed -e 's!.*<title>\(.*\)</title>.*!\1!' | sed 's/\s*-\s*YouTube//' | perl -MHTML::Entities -pe 'decode_entities($_);')
                echo $vid_id >> $SEEN
                notify-send -i 'none' -t 3000 "SUBTUBE" "$title" -u critical -i $THUMBNAILS/$vid_id.jpg
            fi
        done <<< "$vid_ids"
    done < $SUBSCRIBES
    sleep 2
    if [[ $1 != "secret" ]]; then
        notify-send -i 'none' -t 3000 "SUBTUBE" "$(find $THUMBNAILS/* | wc -l) unseen video(s)"
    fi
    rm /tmp/subtube_update.pid
}

pick_thumbnails(){
    [[ $XDG_SESSION_DESKTOP == 'bspwm' ]] && bspc rule -a Sxiv --one-shot sticky=on state=floating rectangle=800x500+560+250
    if [[ $(ls $THUMBNAILS | wc -l) -gt 16 ]] && [[ $XDG_SESSION_DESKTOP == 'bspwm' ]]; then
        notify-send -t 4000 -i 'none' -u low "Warning" "Thumbnails do not fit in sxiv"
    fi
    chosen=$(sxiv -tbo $THUMBNAILS || notify-send -i 'none' -t 3000 "SubTube" "No videos to play")
    if [[ ! -z $chosen ]]; then
        num=$(echo "$chosen" | wc -l)
        i=1
        while read choice; do
            id=$(echo "$choice" | sed "s/\/usr\/share\/subtube\/resources\/thumbnails\/\([^.]\+\)\.jpg/\1/")
            rm $choice
            sed -i "/$id/d" $SUBTUBE_TITLE
            if [[ $1 == "remove" ]]; then
                notify_name "Removing" $id
            else
                if [[ $num -eq 1 ]]; then
                    notify_name "Playing" $id
                else
                    notify_name "Playing $i/$num" $id
                    i=$((i+1))
                fi
                url="https://www.youtube.com/watch?v=$id"
                TITLE=$(wget --quiet -O - $url | sed -n -e 's!.*<title>\(.*\)</title>.*!\1!p')
                echo "$TITLE($url)" >> /home/infiniter/.local/share/qutebrowser/mpv_history
                youtube-viewer --no-interactive --resolution=720p --player=mpv "$url"
            fi
        done <<< "$chosen"
    fi
}

pick_rofi(){
    echo "NotImplementedError"
    exit 1
    if [[ $(cat $SUBTUBE_TITLE | wc -l) -eq 0 ]]; then
        notify-send -i 'none' -t 3000 "SubTube" "Nothing to watch"
    fi
    chosen=$(cat $SUBTUBE_TITLE | sed 's/^[^\ ]*\ *//'| rofi -dmenu -p "Subtube videos" || notify-send -i 'none' -t 3000 "SubTube" "No videos chosen")
    if [[ ! -z $chosen ]]; then
        while read choice; do
            id=$(cat $SUBTUBE_TITLE | sed -n "/$chosen/p" | awk '{print $1}')
            if [[ ! -z $id ]]; then
                sed -i "/$id/d" $SUBTUBE_TITLE
                rm $THUMBNAILS/$id.jpg
            else
                exit 1
            fi
            if [[ $1 == "remove" ]]; then
                notify_name "Removing" $id
            else
                notify_name "Playing" $id
                url="https://www.youtube.com/watch?v=$id"
                TITLE=$(cat $SUBTUBE_TITLE | grep $id | awk '{print $2}')
                echo "$TITLE($url)" >> /home/infiniter/.local/share/qutebrowser/mpv_history
                youtube-viewer --no-interactive --resolution=720p --player=mpv "$url"
            fi
        done <<< "$chosen"
    fi
}

clean(){
    rm ~/.scripts/resources/thumbnails/*
}

name(){
    cutted=$(echo "$1" | sed 's/.*\/\([^.]*\)\.jpg/\1/')
    title=$(wget --quiet -O - "https://www.youtube.com/watch?v=$cutted" | paste -s -d " " | sed -e 's!.*<head>\(.*\)</head>.*!\1!' | sed -e 's!.*<title>\(.*\)</title>.*!\1!' | sed 's/\s*-\s*YouTube//' | perl -MHTML::Entities -pe 'decode_entities($_);')
    notify-send -i 'none' -t 4000 "Title" "$title"
}

add_queue(){
    cutted=$(echo "$1" | sed 's/.*\/\([^.]*\)\.jpg/\1/')
    echo "$cutted" >> $SUBTUBE_QUEUE
    lego_refresh "subtube"
}

play_queue(){
    len=$(cat $SUBTUBE_QUEUE | wc -l)
    if [[ $len -eq 0 ]]; then
        notify-send -i 'none' "Queue" "nothing to play"
        exit 0
    fi
    for i in $(seq 1 $len); do
        id=$(sed -n "1p" $SUBTUBE_QUEUE)
        url="https://www.youtube.com/watch?v=$id"
        TITLE=$(wget --quiet -O - $url\
            | sed -n -e 's!.*<title>\(.*\)</title>.*!\1!p')
        sed -i '1d' $SUBTUBE_QUEUE
        lego_refresh "subtube"
        echo "$TITLE($url)" >> /home/infiniter/.local/share/qutebrowser/mpv_history
        notify-send -i 'none' "Queue playing" "$TITLE"
        youtube-viewer --no-interactive --resolution=720p --player=mpv "$url"
    done
}

notify_name(){
    title=$(wget --quiet -O - "https://www.youtube.com/watch?v=$2" | paste -s -d " " | sed -e 's!.*<head>\(.*\)</head>.*!\1!' | sed -e 's!.*<title>\(.*\)</title>.*!\1!' | sed 's/\s*-\s*YouTube//')
    if [[ $1 == "Playing" ]]; then
        notify-send -i $PLAYING_ICON -t 4000 "$1" "$title"
    else
        notify-send -i 'none' -t 4000 "$1" "$title"
    fi

}

list(){
    subs=$(cat $SUBSCRIBES | wc -l)
    subs_names=$(cat $NAMES | wc -l)
    i=0
    if [[ ! $subs -eq $subs_names ]]; then
        while read sub; do
            i=$(($i+1))
            if [[ $i -le $subs_names ]]; then
                continue
            fi
            name=$(wget --quiet -O - "$sub" | sed -n '/og\:title/p' | sed 's/.*content="\([^"]\+\).*/\1/')
            echo $name >> $NAMES
        done < $SUBSCRIBES
    fi
    cat $NAMES
}

if [[ $1 == 'update' ]]; then
    update
elif [[ $1 == 'secret_update' ]]; then
    update secret
elif [[ $1 == 'init' ]]; then
    update init
elif [[ $1 == 'viewer' ]]; then
    viewer
elif [[ $1 == 'play' ]]; then
    pick_thumbnails
elif [[ $1 == 'add_queue' ]]; then
    add_queue $2
elif [[ $1 == 'play_queue' ]]; then
    play_queue
elif [[ $1 == 'rofi_play' ]]; then
    pick_rofi
elif [[ $1 == 'remove' ]]; then
    pick_thumbnails remove
elif [[ $1 == 'clean' ]]; then
    clean
elif [[ $1 == 'name' ]]; then
    name $2
elif [[ $1 == 'add' ]]; then
    echo $2 >> $SUBSCRIBES
elif [[ $1 == 'list' ]]; then
    list
else
    echo "Usage: subtube [OPTION]"
    echo "Youtube interface without browser"
    echo ""
    echo "Options:"
    echo "  -h, --help                 show this message and quit"
    echo "  update                     update database"
    echo "  secret_update              update database without notification"
    echo "  init                       initial start, just fill db with old videos"
    echo "  play                       sxiv -t selection"
    echo "  add_queue                  add item to queue (sxiv keyhandler)"
    echo "  play_queue                 play videos in queue"
    echo "  rofi_play                  rofi selection"
    echo "  remove                     remove selected options"
    echo "  clean                      cleans downloaded thumbnails"
    echo "  name                       notify-send name of video"
    echo "  add                        add subscriber"
    echo "  list                       list all subscriber names"
fi
